approval_policy = "on-failure"
model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
sandbox_mode = 'danger-full-access'

[features]
multi_agent = true

[mcp_servers]
[mcp_servers.MCP_DOCKER]
command = 'docker.exe'
args = ['mcp', 'gateway', 'run']
enabled = false

[mcp_servers.figma]
url = 'https://mcp.figma.com/mcp'

[mcp_servers.linear]
bearer_token_env_var = 'lin_api_aTOP0h6h08ca0o90ITO3yLshzK11C2J3D95tTgBx'
url = 'https://mcp.linear.app/mcp'

[mcp_servers.notion]
url = 'https://mcp.notion.com/mcp'

[mcp_servers.playwright]
args = ['@playwright/mcp@latest']
command = 'npx'

[mcp_servers.avalonia-docs]
enabled = true
url = "https://docs-mcp.avaloniaui.net/mcp"

[mcp_servers.avalonia-docs.tools.get_avalonia_expert_rules]
approval_mode = "approve"

[mcp_servers.avalonia_parcel]
args = ["mcp"]
command = "parcel"
enabled = true

[mcp_servers.avalonia_parcel.env]
PARCEL_LICENSE_KEY = "avln_on_key:v1:18413446031b485b85664c459479099a"

[projects]
[projects.'C:\Users\ander']
trust_level = 'trusted'

[projects.'\\?\C:\Users\ander\automod-studio']
trust_level = 'trusted'

[projects.'D:\Dev\Babel-Player']
trust_level = 'trusted'

[projects.'\\?\D:\Dev\Babel-Player']
trust_level = 'trusted'


[skills]
[windows]
sandbox = 'elevated'

[plugins."github@openai-curated"]
enabled = true

[plugins."canva@openai-curated"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."hugging-face@openai-curated"]
enabled = true

[apps.asdk_app_6939e86417648191b7bda087d872685b]
enabled = false

[mcp_servers.context7]
type = "http"
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "ctx7sk-0c017af9-1193-4cfe-b9eb-a30de691eef6"
