global using System;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using BabelPlayer.App;
global using HardwareDecodingMode = BabelPlayer.App.ShellHardwareDecodingMode;
global using IBabelLogFactory = BabelPlayer.App.IAppLogFactory;
global using IBabelLogger = BabelPlayer.App.IAppLogger;
global using IAppDiagnosticsContext = BabelPlayer.App.IAppDiagnosticsState;
global using MediaTrackInfo = BabelPlayer.App.ShellMediaTrack;
global using MediaTrackKind = BabelPlayer.App.ShellMediaTrackKind;
global using PlaybackQueueSnapshot = BabelPlayer.App.ShellQueueSnapshot;
global using PlaybackStateSnapshot = BabelPlayer.App.ShellPlaybackStateSnapshot;
global using PlaybackWindowMode = BabelPlayer.App.ShellPlaybackWindowMode;
global using PlaylistItem = BabelPlayer.App.ShellPlaylistItem;
global using RuntimeInstallProgress = BabelPlayer.App.ShellRuntimeInstallProgress;
global using ShortcutProfile = BabelPlayer.App.ShellShortcutProfile;
global using SubtitleRenderMode = BabelPlayer.App.ShellSubtitleRenderMode;
global using SubtitleStyleSettings = BabelPlayer.App.ShellSubtitleStyle;
global using BabelLogContext = BabelPlayer.App.AppLogContext;
