// <auto-generated>
//     Strongly-typed accessor for Resources/Strings.resx.
//
//     ResXFileCodeGenerator is a Visual Studio custom-tool integration that is
//     not available from the dotnet CLI, so this file is maintained by hand in
//     a shape that matches its output.  When new keys are added to
//     Resources/Strings.resx (via scripts/build_strings_resx.py), new
//     properties may be added here or the <see cref="ResourceManager"/> can be
//     used directly through <see cref="Babel.Player.Services.LocalizationService"/>.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace Babel.Player.Resources;

/// <summary>Strongly-typed accessor for the app's localized UI strings.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Resource manager bound to <c>Babel.Player.Resources.Strings.resources</c>.</summary>
    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "Babel.Player.Resources.Strings",
            typeof(Strings).Assembly);

    /// <summary>Culture used for free-form lookups that do not pass an explicit culture.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Returns the localized string for <paramref name="key"/>, or <c>[key]</c> when missing.</summary>
    public static string Get(string key) =>
        ResourceManager.GetString(key, Culture) ?? $"[{key}]";
}
