#!/usr/bin/env python3
"""
Aggregate all benchmark result files in docs/benchmarks/ into a leaderboard.

Reads every *.json file in docs/benchmarks/, groups results by matrix × machine,
and writes docs/benchmarks/LEADERBOARD.md with a sorted summary table.

Usage:
  python scripts/aggregate_leaderboard.py
  python scripts/aggregate_leaderboard.py --benchmarks-dir path/to/dir
"""

from __future__ import annotations

import argparse
import json
import statistics
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass
class ResultRow:
    timestamp: str          # ISO timestamp from filename
    machine_id: str
    cpu: str
    gpu: str
    provider: str
    model: str
    matrix_id: str
    dataset_id: str
    variant: str
    cache_mode: str
    measured_runs: int
    mean_s: float
    p50_s: float
    p95_s: float
    segment_count: int
    run_batch_id: str


def parse_timestamp(filename: str) -> str:
    """Extract ISO timestamp from benchmark filename (first token before _)."""
    return filename.split("_")[0]


def load_results(benchmarks_dir: Path) -> list[ResultRow]:
    rows: list[ResultRow] = []
    for path in sorted(benchmarks_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  SKIP {path.name}: parse error — {e}")
            continue

        results = data.get("results", [])
        if not results:
            continue  # shell file with no measurements yet

        env = data.get("environment_snapshot", {})
        inp = data.get("normalized_inputs", {})
        ts = parse_timestamp(path.stem)

        for r in results:
            variant_obj = r.get("variant", {})
            timings = r.get("timings_seconds", [])
            mean_s = r.get("mean_seconds") or (statistics.mean(timings) if timings else None)
            p50_s = r.get("p50_seconds") or (statistics.median(timings) if timings else None)
            p95_s = r.get("p95_seconds")
            if p95_s is None and len(timings) >= 2:
                sorted_t = sorted(timings)
                idx = int(len(sorted_t) * 0.95)
                p95_s = sorted_t[min(idx, len(sorted_t) - 1)]

            if mean_s is None:
                continue

            rows.append(ResultRow(
                timestamp=ts,
                machine_id=env.get("MachineId", "unknown"),
                cpu=env.get("CPU", ""),
                gpu=env.get("GPU", ""),
                provider=inp.get("provider", ""),
                model=inp.get("model", ""),
                matrix_id=inp.get("matrix_id", ""),
                dataset_id=inp.get("dataset_id", ""),
                variant=variant_obj.get("label", ""),
                cache_mode=r.get("cache_mode", ""),
                measured_runs=r.get("measured_runs", 0),
                mean_s=mean_s,
                p50_s=p50_s or mean_s,
                p95_s=p95_s or mean_s,
                segment_count=r.get("segment_count", 0),
                run_batch_id=inp.get("run_batch_id", ""),
            ))

    return rows


def best_per_key(rows: list[ResultRow]) -> list[ResultRow]:
    """For each (machine, matrix, variant, cache_mode), keep the row with the lowest mean."""
    best: dict[tuple, ResultRow] = {}
    for row in rows:
        key = (row.machine_id, row.matrix_id, row.variant, row.cache_mode)
        if key not in best or row.mean_s < best[key].mean_s:
            best[key] = row
    return sorted(best.values(), key=lambda r: (r.matrix_id, r.cache_mode, r.mean_s))


def fmt_s(v: float) -> str:
    return f"{v:.3f}s"


def short_matrix(matrix_id: str) -> str:
    """Strip the bp.matrix. prefix and version suffix for display."""
    s = matrix_id.removeprefix("bp.matrix.")
    # strip trailing .vX.Y.Z
    parts = s.rsplit(".", 1)
    if len(parts) == 2 and parts[1].startswith("v"):
        s = parts[0]
    return s


def short_dataset(dataset_id: str) -> str:
    s = dataset_id.removeprefix("bp.dataset.")
    parts = s.rsplit(".", 1)
    if len(parts) == 2 and parts[1].startswith("v"):
        s = parts[0]
    return s


def build_markdown(rows: list[ResultRow], all_rows: list[ResultRow]) -> str:
    best = best_per_key(rows)

    # Group by matrix_id for separate tables
    matrices: dict[str, list[ResultRow]] = {}
    for row in best:
        matrices.setdefault(row.matrix_id, []).append(row)

    lines: list[str] = [
        "# Benchmark Leaderboard",
        "",
        "Auto-generated by `scripts/aggregate_leaderboard.py`. "
        "Each table shows the best measured run per machine × variant × cache mode.",
        "",
        f"**Result files:** {len(set(r.run_batch_id for r in all_rows))} batches across "
        f"{len(set(r.machine_id for r in all_rows))} machine(s).",
        "",
    ]

    for matrix_id, mrows in sorted(matrices.items()):
        dataset_id = mrows[0].dataset_id
        lines += [
            f"## {short_matrix(matrix_id)}",
            "",
            f"**Matrix:** `{matrix_id}`  ",
            f"**Dataset:** `{short_dataset(dataset_id)}`",
            "",
            "| Machine | CPU | GPU | Variant | Cache | Runs | Mean | p50 | p95 |",
            "|---------|-----|-----|---------|-------|------|------|-----|-----|",
        ]
        for r in sorted(mrows, key=lambda x: (x.cache_mode, x.mean_s)):
            cpu_short = r.cpu.replace(" Processor", "").replace("-Core", "c")
            gpu_short = r.gpu.replace("NVIDIA ", "").replace("GeForce ", "")
            lines.append(
                f"| `{r.machine_id}` | {cpu_short} | {gpu_short} "
                f"| {r.variant} | {r.cache_mode} | {r.measured_runs} "
                f"| {fmt_s(r.mean_s)} | {fmt_s(r.p50_s)} | {fmt_s(r.p95_s)} |"
            )
        lines.append("")

    lines += [
        "---",
        "",
        "_To add your results: run `python scripts/run_cpu_transcription_benchmark.py`, "
        "commit the JSON file to `docs/benchmarks/`, and open a PR._",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate benchmark results into a leaderboard.")
    parser.add_argument(
        "--benchmarks-dir",
        type=Path,
        default=REPO_ROOT / "docs" / "benchmarks",
        help="Directory containing benchmark JSON files (default: docs/benchmarks/)",
    )
    args = parser.parse_args()

    benchmarks_dir: Path = args.benchmarks_dir
    if not benchmarks_dir.is_dir():
        print(f"ERROR: benchmarks dir not found: {benchmarks_dir}")
        raise SystemExit(1)

    print(f"Scanning {benchmarks_dir} ...")
    all_rows = load_results(benchmarks_dir)
    print(f"  {len(all_rows)} result row(s) loaded from "
          f"{len(list(benchmarks_dir.glob('*.json')))} JSON file(s).")

    if not all_rows:
        print("No results with measurements found — leaderboard will be empty.")

    md = build_markdown(all_rows, all_rows)
    out_path = benchmarks_dir / "LEADERBOARD.md"
    out_path.write_text(md, encoding="utf-8")
    print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
