#!/usr/bin/env python3
"""Write a satellite ``Resources/Strings.<lang>.resx`` using the same schema
header as :mod:`build_strings_resx`.

Designed for manual verification (Phase 1.9) and as a building block for the
Tools/LocaleGenerator console tool (Phase 2).  Keys that are not passed in are
omitted, so the resource manager falls back to the English base for anything
missing.
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Dict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_strings_resx import RESX_HEADER, _escape  # type: ignore[import]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def write_locale(lang: str, entries: Dict[str, str]) -> str:
    path = os.path.join(REPO_ROOT, "Resources", f"Strings.{lang}.resx")
    lines = [RESX_HEADER]
    for key in sorted(entries.keys()):
        value = entries[key]
        lines.append(f'  <data name="{_escape(key)}" xml:space="preserve">')
        lines.append(f'    <value>{_escape(value)}</value>')
        lines.append('  </data>')
    lines.append('</root>')
    lines.append('')
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


# Handful of German translations used to verify the localization pipeline
# end-to-end.  The full satellite will be generated by
# Tools/LocaleGenerator in Phase 2.
GERMAN_VERIFICATION: Dict[str, str] = {
    "Common_Cancel": "Abbrechen",
    "Common_Close": "Schlie\u00dfen",
    "Common_Save": "Speichern",
    "Common_Clear": "Leeren",
    "Common_Ok": "OK",
    "Common_Apply": "Anwenden",
    "Common_Browse": "Durchsuchen",
    "Common_Download": "Herunterladen",
    "Common_Restart": "Neu starten",
    "Window_Title_Main": "Babel Player",
    "Window_Title_Settings": "Babel Player - Einstellungen",
    "Window_Title_ApiKeys": "API-Schl\u00fcssel",
    "Window_Title_Crash": "Babel Player - Unbehandelter Fehler",
    "Window_Title_Wizard": "Lautsprecher-Referenz-Assistent",
    "Section_Translation": "\u00dcBERSETZUNG",
    "Section_Transcription": "TRANSKRIPTION",
    "Automation_RerunTranscription": "Transkription erneut ausf\u00fchren",
    "Automation_RerunDiarization": "Sprecherzuordnung erneut ausf\u00fchren",
    "Automation_RerunTranslation": "\u00dcbersetzung erneut ausf\u00fchren",
    "Automation_RerunDub": "Dub-Audio neu erzeugen",
    "Automation_ExpandErrorDetails": "Fehlerdetails erweitern",
    "Label_SegmentCount_One": "{0} Segment",
    "Label_SegmentCount_Many": "{0} Segmente",
    "SpokenLanguage_AutoDetect": "Automatisch erkennen",
    "Automation_RefreshSegments": "Segmente aktualisieren",
    "Settings_Group_AppLanguage": "App-Sprache",
    "Settings_Hint_AppLanguage":
        "\u00c4ndert die Sprache der Benutzeroberfl\u00e4che des Babel Players. "
        "Auto (System) folgt bei jedem Start dem Gebietsschema Ihres Betriebssystems.",
    "Settings_Option_AutoSystem": "Auto (System)",
    "Settings_Button_SaveClose": "Speichern und schlie\u00dfen",
    "Crash_Header": "Ein unbehandelter Fehler ist aufgetreten",
    "Crash_Button_Copy": "In die Zwischenablage kopieren",
    "Crash_Button_OpenLogFolder": "Log-Ordner \u00f6ffnen",
    "Crash_Button_Close": "Schlie\u00dfen",
    "Language_de": "Deutsch",
    "Language_en": "Englisch",
    "Language_fr": "Franz\u00f6sisch",
    "Language_es": "Spanisch",
    "Language_it": "Italienisch",
    "Language_ja": "Japanisch",
    "Language_ko": "Koreanisch",
    "Language_nl": "Niederl\u00e4ndisch",
    "Language_pl": "Polnisch",
    "Language_pt": "Portugiesisch",
    "Language_ru": "Russisch",
    "Language_sv": "Schwedisch",
    "Language_tr": "T\u00fcrkisch",
    "Language_ar": "Arabisch",
    "Language_hi": "Hindi",
    "Language_zh": "Chinesisch (vereinfacht)",
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lang", nargs="?", default="de",
                        help="ISO 639-1 language code (default: de)")
    args = parser.parse_args()
    if args.lang == "de":
        path = write_locale("de", GERMAN_VERIFICATION)
        print(f"Wrote {len(GERMAN_VERIFICATION)} keys to {path}")
    else:
        raise SystemExit(
            f"No verification payload for '{args.lang}'. "
            "Use Tools/LocaleGenerator for the full set of satellite files."
        )


if __name__ == "__main__":
    main()
